[tool.poetry]
name = "python-microservice-starter"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.9"
connexion = { extras = ["swagger-ui"], version = "^2.14.1" }
python-dotenv = "^1.0.0"
flask-cors = "^3.0.10"
flask-request-id-middleware = "^1.1"
flask-compress = "^1.13"
waitress = "^2.1.2"
pymysql = "^1.0.2"
cryptography = "^38.0.3"
pandas = "^2.0.1"
pydantic = "^1.10.2"
paste = "^3.5.2"
sqlalchemy = "^2.0.4"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"
black = "^23.1.0"
isort = "^5.10.1"
pytest = "^7.2.0"
types-waitress = "^2.1.4.1"
mypy = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = "./tests"
addopts = "-v"
