[project]
name = "python-microservice-starter"
version = "0.1.0"
description = ""
authors = [{ name = "Your Name", email = "you@example.com" }]
readme = "README.md"
requires-python = ">=3.13"
scripts = { dev = "app.dev_server:start" }
dependencies = [
  "connexion[flask,swagger-ui,uvicorn] (>=3.2.0,<4.0.0)",
  "python-dotenv (>=1.1.1,<2.0.0)",
  "flask-cors (>=6.0.1,<7.0.0)",
  "flask-compress (>=1.17,<2.0)",
  "pymysql (>=1.1.1,<2.0.0)",
  "cryptography (>=46.0.1,<47.0.0)",
  "pandas (>=2.3.0,<3.0.0)",
  "pydantic (>=2.11.7,<3.0.0)",
  "pydantic-settings (>=2.10.1,<3.0.0)",
  "sqlalchemy (>=2.0.41,<3.0.0)",
]

[dependency-groups]
dev = [
    "pytest (>=8.4.2,<9.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
requires-poetry = ">=2.2"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = ">=3.13,<4.0"

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
addopts = ["-v", "-s"]
